#!/bin/bash
. "${HOME}/.cache/wal/colors.sh"

dmenu_path | \
    dmenu "$@" -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15" \
    -p ' > ' -fn 'xos4 Terminus:size=11' \
    | ${SHELL:-"/bin/sh"} &
