#!/bin/sh
# kiedtl's bspwmrc

. "${HOME}/.cache/wal/colors.sh"

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc config window_gap 16
bspc config top_padding 48
bspc config border_width 2
bspc config border_radius 7

bspc config pointer_modifier mod1

bspc config single_monocle true
bspc config gapless_monocle true
bspc config borderless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false

bspc rule -a feh state=floating
bspc rule -a scratchpad sticky=on state=floating hidden=on

# -----

(
	xmodmap -e "clear lock"
	xmodmap -e "keycode 9 = Caps_Lock NoSymbol Caps_Lock"
	xmodmap -e "keycode 66 = Escape NoSymbol Escape"
) &

(
	polybar left
	polybar center
	polybar right
) &

(xrdb -merge ~/etc/Xorg/.Xresources) &
(wal -R) &
(xautolock -time 30 -locker slock) &
(sxhkd) &
