#!/bin/sh
# kiedtl's bspwmrc

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap 16
bspc config border_width 0
bspc config border_radius 7

bspc config pointer_modifier mod1

bspc config single_monocle true
bspc config gapless_monocle false
bspc config borderless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false

bspc config normal_border_color "#2f364a"
bspc config focused_border_color "#ffffff"

bspc rule -a feh state=floating

# -----

(
	xmodmap -e "clear lock"
	xmodmap -e "keycode 9 = Caps_Lock NoSymbol Caps_Lock"
	xmodmap -e "keycode 66 = Escape NoSymbol Escape"
) &

(xrdb -merge ~/etc/Xorg/.Xresources) &
(~/.fehbg) &
(xautolock -time 30 -locker slock) &
