#!/bin/sh
# kiedtl's bspwmrc

bspc monitor -d 0 1 2 3 4 5 6 7 8 9

bspc config window_gap 16
bspc config top_padding 24
bspc config border_width 0
bspc config border_radius 7

bspc config pointer_modifier mod1

bspc config single_monocle true
bspc config gapless_monocle false
bspc config borderless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false

bspc config normal_border_color "#2f364a"
bspc config focused_border_color "#ffffff"

bspc rule -a feh state=floating
bspc rule -a scratchpad sticky=on state=floating hidden=on

# -----

(
	xmodmap -e "clear lock"
	xmodmap -e "keycode 9 = Caps_Lock NoSymbol Caps_Lock"
	xmodmap -e "keycode 66 = Escape NoSymbol Escape"
) &

(xrdb -merge ~/etc/Xorg/.Xresources) &
(~/.fehbg) &
(xautolock -time 30 -locker slock) &

scratch init
